### ISSUE TITLE
Plugin uses user preference timezone rather than server timezone.

### ISSUE THREAD

**Issue by doiphode** [isuru89/moodle-local_reminders#159] opened 2022-09-28 22:17 UTC
The reminders use user's preference for timezone to send out notifications.

This creates an issue if the user is using GMT rather than BST.

**Comment by isuru89** [comment] 2022-09-29 04:26
Thanks for the suggestion.
Will include the changes in next release.

**Comment by isuru89** [comment] 2022-09-29 04:27
@doiphode Would you kindly change the destination branch of the pull request to `release_2.0`. because, regression is done there.

**Comment by doiphode** [comment] 2022-09-29 10:30
@isuru89 I have created a new pull request (#161) as per your suggestion.

**Comment by isuru89** [comment] 2022-11-08 01:54
Released with plugin v2.7

**Closed by isuru89** 2022-11-08 01:54 UTC

**Comment by doiphode** [comment] 2022-11-27 20:44
Thanks very much!
