### ISSUE TITLE
Multiple emails received by users when a recurring event is created or updated or removed

### ISSUE THREAD

**Issue by flowersofpepper** [isuru89/moodle-local_reminders#184] opened 2024-07-26 15:22 UTC
**Describe the bug (required)**
I have identified a bug in this module. When an event is set to repeat more than one time, and the "update or remove or create notification" setting is enabled, the system sends more than one separate email to the student whenever we update remove or create all events in the series. This results in the student receiving excessive emails, which can be perceived as spam and inconvenient.

**To Reproduce (required)**
1. Turn on "Calendar Events Change Reminders" from the setting in Site administration 
2. Create a recurring event for a course or group or edit any one event within the recurring events by selecting the option "Also apply changes to the other ... events in this repeat series"
3. Click save.

Please note: All enrolled users will receive an individual email notification for each event update in the series. For example, if there are 5 events, they will receive 5 emails; if there are 30 events, they will receive 30 emails.

**Expected behavior (required)**
To address this, we must ensure the system sends a single, consolidated email to the student instead of multiple individual notifications. This will enhance the user experience and maintain a professional communication standard.

**Environment (required):**
 - Moodle version: 4.4
 - Database: MySQL
 - PHP Version: 8.2

**Comment by flowersofpepper** [comment] 2024-08-20 03:48
@isuru89 Any update on this

**Comment by isuru89** [comment] 2024-08-21 00:38
@flowersofpepper I did not have a chance to look into this yet due to other work. I will look into this during this weekend. Thank you for reporting.

**Comment by isuru89** [comment] 2024-08-22 04:25
@flowersofpepper Just a small question. 
Do the intervals between two events in this series less than 7 days? Something like, daily?

**Comment by flowersofpepper** [comment] 2024-08-22 07:55
@isuru89 no weekly events

**Comment by flowersofpepper** [comment] 2024-08-23 04:06
@isuru89 I checked it's happening both with weekly and daily events.

**Comment by isuru89** [comment] 2024-08-24 01:28
@flowersofpepper I managed to reproduce this and currently working on a fix.

**Comment by isuru89** [comment] 2024-08-24 03:17
This has been fixed with plugin version v2.7.3, Please reopen this if the issue persist again.

**Closed by isuru89** 2024-08-24 03:17 UTC
Labels: bug

**Comment by flowersofpepper** [comment] 2024-08-25 09:04
Thank you, I will check it in dev and let you know soon.

**Comment by flowersofpepper** [comment] 2024-08-27 20:33
@isuru89 

I have identified a few NEW ISSUES related to this same issue, which are outlined below:

1. When a particular event in a series is deleted, two separate emails are sent to the customer: one stating that the event has been removed, and another indicating that the event has been updated with the date and time of the next occurrence in the series which may not be the next occurrence of that particular event because sometimes we will be scheduling an event later so the second event updated email is unnecessary.

2. Secondly, no email notifications are sent when an event is updated or deleted within a series that was once either updated or deleted before. 

3. A notification happens again if we delete the event in which an updated notification was received while deleting in the first place, which I mentioned in the first issue. 

4. Also a notification is sent again if the first event that was updated is updated multiple times. However, aside from these two scenarios, no email notifications are sent after an update or removal notification has been received for a particular recurring series once.

5. I also noticed that there is a delay in updation or deletion if we update a series that has a lot of recurring events in the series, that means the separate notifications are created in the background but the only thing is that the emails are not getting sent. 

An issue closed by the owner can't be opened again by the author so can you please reopen this for me thank you.

**Comment by isuru89** [comment] 2024-08-28 03:36
@flowersofpepper Thank you for feedback.

Generally, this plugin (as it names implies) should do ONLY send reminders in defined schedules advance to the approaching deadlines (or notify about missed deadlines) instead of sending emails as soon as a calendar event created/updated/removed. This functionality was added with #44 as a complementary enhancement. In an ideal world, Moodle core itself should at least send emails as soon as an event is created/updated/removed.

I have already identified that this is the most least used feature by the community. 
But aside from that, I have created a new ticket #190 to tackle this separately as this might require a change in design how to handle with recurring events. And, as title says, this suppose to fix the duplication.

Although I assume the plugin's "true-purpose", that is sending reminders just before the deadline, are processing correctly as of now regardless of it is an recurring or not.

**Comment by flowersofpepper** [comment] 2024-08-29 02:37
@isuru89 

I agree that Moodle Core should handle notifications for event creation, updates, and deletions by default. 

I appreciate your efforts in adding the complementary functionality with #44 and understand the intention behind it. It's helpful to know that you're aware of the challenges with handling recurring events and have already created a ticket (#190) to address this. 

Thank you for continuing to improve the plugin and address these issues. Your work is truly appreciated!
