### ISSUE TITLE
"No reminders once completed" option ignored

### ISSUE THREAD

**Issue by zozo1977** [isuru89/moodle-local_reminders#108] opened 2021-03-08 14:20 UTC
"No reminders once completed" option is ignored. Reminders are sent for future activitie events rgardles of this option. 
I tested with clean Moodle installation v3.7.9., and plugin version 2.2.4  (2021030800)

Steps I took while testing:

1. Created new course
2. Created 2 File resources and 2 Page resources. 
3. Set expected completion date dor all 4 resources
4. Set completion criteria "User has to view the activity" for all 4 resources
3. Created two user accounts
4. Enrolled both user account to the course with default Student role
5. Logged in with one user, opened first 2 resources so both reources became completed for that user
6. Logged in with second user, opened the other 2 resources so both reources became completed for that user
7. Ran Local Reminder scheduled task that triggered sending email reminders. 8 emails sent instead of 4.
8. Checked inboxes for both users. Both users received reminders for all 4 activities (two completed and the other two incomplete)

**Comment by zozo77** [comment] 2021-04-19 07:16
Hello! Have any steps been taken on this issue? If not, is there any timeframe defined for resolving it? 
Thanks!
Z.

**Comment by isuru89** [comment] 2021-04-22 03:32
@zozo1977 will try to reproduce and fix  when I get some free time. Little bit busy these days.

**Comment by isuru89** [comment] 2021-04-22 15:42
@zozo77 Page and file resource completion is not yet supported by this plugin, because I could not find external apis from those plugins to filter out completed criteria's against users.

I would be grateful if you can point me if there any noodle documentation regarding to those plugins.
Currently supported plugins for completion status ar here https://github.com/isuru89/moodle-local_reminders/blob/master/contents/activity_handlers.class.php

**Comment by isuru89** [comment] 2021-04-25 03:39
Related to #113

**Comment by isuru89** [comment] 2021-04-25 05:18
This could be fixed with #113 .
Hence closing this ticket. And refer #113 for the status

**Closed by isuru89** 2021-04-25 05:18 UTC
